(function(g){var window=this;var spa=function(a,b){return g.Ub(a,b)},b4=function(){},tpa=function(a){if(a.uc&&"function"==typeof a.uc)return a.uc();
if(g.v(a))return a.split("");if(g.Ka(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},upa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ka(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Fd&&"function"==typeof a.Fd)var c=a.Fd();else if(a.uc&&"function"==typeof a.uc)c=void 0;else if(g.Ka(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=tpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},c4=function(a){g.en(a,"zx",g.rc());
return a},d4=function(a,b,c){g.Ja(c)||(c=[String(c)]);
g.kn(a.l,b,c)},e4=function(a){return(a=g.Bo(a))?new ActiveXObject(a):new XMLHttpRequest},f4=function(a,b){return b+" ["+a.ba+" "+a.F+" "+a.getStatus()+"]"},vpa=function(a){return"content-type"==a.toLowerCase()},g4=function(a){a.g&&a.J&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},wpa=function(a){return g.Md&&g.Cc(9)&&g.Da(a.timeout)&&g.Ba(a.ontimeout)},h4=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},i4=function(a,b){if(a.g){g4(a);
var c=a.g,d=a.P[0]?g.Fa:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},j4=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;h4(a);i4(a)},k4=function(a){return a.g?a.g.readyState:0},l4=function(a){if(a.i&&"undefined"!=typeof g.LX)if(a.P[1]&&4==k4(a)&&2==a.getStatus())f4(a,"Local request error detected and ignored");
else if(a.D&&4==k4(a))g.Dg(a.Xv,0,a);else if(a.dispatchEvent("readystatechange"),4==k4(a)){f4(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Ng(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!xpa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<k4(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";h4(a)}}finally{i4(a)}}},m4=function(a){g.Qf.call(this);
this.headers=new g.Um;this.M=a||null;this.i=!1;this.P=this.g=null;this.ba=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.B=null;this.Y="";this.J=this.R=!1},n4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},ypa=function(a,b){var c=[];
g.Wk(b,function(d){try{var e=g.Qo.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ba(e)?g.Po(e)&&c.push(d):c.push(d)},a);
return c},zpa=function(a,b){var c=ypa(a,b);
(0,g.B)(c,function(d){g.Qo.prototype.remove.call(this,d)},a)},o4=function(a){if(a.bd){if(a.bd.locationOverrideToken)return{locationOverrideToken:a.bd.locationOverrideToken};
if(null!=a.bd.latitudeE7&&null!=a.bd.longitudeE7)return{latitudeE7:a.bd.latitudeE7,longitudeE7:a.bd.longitudeE7}}return null},Apa=function(a,b){g.$a(a,b)||a.push(b)},p4=function(a){var b=0,c;
for(c in a)b++;return b},Bpa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},Cpa=function(a){try{return g.w.JSON.parse(a)}catch(d){var b=d}a=String(a);
if(Bpa(a))try{var c=eval("("+a+")");b&&(0,g.LW)("Invalid JSON: "+a,b);return c}catch(d){}throw Error("Invalid JSON string: "+a);},Dpa=function(a,b,c,d){var e=new g.Xm(null,void 0);
a&&g.Ym(e,a);b&&g.Zm(e,b);c&&g.$m(e,c);d&&(e.i=d);return e},q4=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return Cpa(a)},r4=function(){this.g=[];
this.i=[]},s4=function(a,b){g.Vp[a]=!0;
var c=g.Tp();c&&c.publish.apply(c,arguments);g.Vp[a]=!1},t4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Um;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Epa(this,a.capabilities||""),Fpa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Epa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Ra(spa,Gpa)).forEach(function(c){a.capabilities.add(c)})},Fpa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},u4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},v4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},w4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Hpa=function(a){return new u4(a)},x4=function(a){return g.Ja(a)?(0,g.F)(a,Hpa):[]},y4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},z4=function(a){return g.Ja(a)?"["+(0,g.F)(a,y4).join(",")+"]":"null"},A4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Ipa=function(a){return(0,g.F)(a,function(b){return{key:b.id,
name:b.name}})},B4=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},C4=function(a,b){return g.Xa(a,function(c){return v4(c,b)})},Jpa=function(){var a=(0,g.et)();
a&&zpa(a,a.g.cf(!0))},D4=function(){var a=g.ht("yt-remote-connected-devices")||[];
g.qb(a);return a},Kpa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.F)(a,function(d,e){return 0==e?d:d.substring(c.length)})},E4=function(a){g.gt("yt-remote-connected-devices",a,86400)},G4=function(){if(F4)return F4;
var a=g.ht("yt-remote-device-id");a||(a=A4(),g.gt("yt-remote-device-id",a,31536E3));for(var b=D4(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return F4=d},H4=function(){var a=D4(),b=G4();
g.$a(a,b);g.jt()&&g.sb(a,b);a=Kpa(a);if(0==a.length)try{g.Gs("remote_sid")}catch(c){}else try{g.Fs("remote_sid",a.join(","),-1)}catch(c){}},I4=function(){return g.ht("yt-remote-session-browser-channel")},J4=function(){return g.ht("yt-remote-local-screens")||[]},K4=function(){g.gt("yt-remote-lounge-token-expiration",!0,86400)},Lpa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.F)(J4(),function(d){return d.loungeToken}),c=(0,g.F)(a,function(d){return d.loungeToken});
(0,g.Ri)(c,function(d){return!g.$a(b,d)})&&K4();
g.gt("yt-remote-local-screens",a,31536E3)},Mpa=function(a,b){g.gt("yt-remote-session-browser-channel",a);
g.gt("yt-remote-session-screen-id",b);var c=D4(),d=G4();g.$a(c,d)||c.push(d);E4(c);H4()},L4=function(a){a||(g.it("yt-remote-session-screen-id"),g.it("yt-remote-session-video-id"));
H4();a=D4();g.cb(a,G4());E4(a)},N4=function(){if(!M4){var a=g.$o();
a&&(M4=new g.Ko(a))}return M4?!!M4.get("yt-remote-use-staging-server"):!1},O4=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},P4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},R4=function(a){a.length?Q4(a.shift(),function(){R4(a)}):S4()},Npa=function(a){return"chrome-extension://"+a+T4},Q4=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},S4=function(){var a=P4();
a&&a(!1,"No cast extension found")},U4=function(){if(Opa){var a=2,b=P4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Q4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",S4,c)}},Ppa=function(){U4();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);R4(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+T4,"//www.gstatic.com/eureka/clank"+T4])},V4=function(a,b,c){g.G.call(this);
this.A=null!=c?(0,g.z)(a,c):a;this.Wc=b;this.u=(0,g.z)(this.KC,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},W4=function(){},X4=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ca=new g.ln(this);this.i=new g.Cg;this.i.setInterval(250)},Z4=function(a,b,c){a.Ph=1;
a.Zf=c4(b.clone());a.jh=c;a.u=!0;Y4(a,null)},$4=function(a,b,c,d,e){a.Ph=1;
a.Zf=c4(b.clone());a.jh=null;a.u=c;e&&(a.Iz=!1);Y4(a,d)},Y4=function(a,b){a.wi=(0,g.C)();
a5(a);a.rg=a.Zf.clone();d4(a.rg,"t",a.A);a.Rk=0;a.oc=a.g.pp(a.g.Jk()?b:null);0<a.Sp&&(a.tn=new g.El((0,g.z)(a.RA,a,a.oc),a.Sp));a.ca.da(a.oc,"readystatechange",a.tL);var c=a.Mg?g.bc(a.Mg):{};a.jh?(a.eo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.oc.send(a.rg,a.eo,a.jh,c)):(a.eo="GET",a.Iz&&!g.Od&&(c.Connection="close"),a.oc.send(a.rg,a.eo,null,c));a.g.me(1)},h5=function(a,b,c){for(var d=!0;!a.Dg&&a.Rk<c.length;){var e=Qpa(a,c);
if(e==b5){4==b&&(a.ag=4,c5(15),d=!1);break}else if(e==d5){a.ag=4;c5(16);d=!1;break}else e5(a,e)}4==b&&0==c.length&&(a.ag=1,c5(17),d=!1);a.se=a.se&&d;d||(f5(a),g5(a))},Qpa=function(a,b){var c=a.Rk,d=b.indexOf("\n",c);
if(-1==d)return b5;c=Number(b.substring(c,d));if(isNaN(c))return d5;d+=1;if(d+c>b.length)return b5;var e=b.substr(d,c);a.Rk=d+c;return e},k5=function(a,b){a.wi=(0,g.C)();
a5(a);var c=b?window.location.hostname:"";a.rg=a.Zf.clone();g.en(a.rg,"DOMAIN",c);g.en(a.rg,"t",a.A);try{a.ue=new ActiveXObject("htmlfile")}catch(n){f5(a);a.ag=7;c5(22);g5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in i5)k=i5[l];else if(l in j5)k=i5[l]=j5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
i5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.jd(g.Kc("b/12014412"),d+"</body></html>");a.ue.open();a.ue.write(g.gd(c));a.ue.close();a.ue.parentWindow.m=(0,g.z)(a.LK,a);a.ue.parentWindow.d=(0,g.z)(a.Ty,a,!0);a.ue.parentWindow.rpcClose=(0,g.z)(a.Ty,a,!1);c=a.ue.createElement("DIV");a.ue.parentWindow.document.body.appendChild(c);d=g.Wc(a.rg.toString());d=g.nc(g.Tc(d));d=g.jd(g.Kc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.kd(c,d);a.g.me(1)},a5=function(a){a.Zs=(0,g.C)()+a.o;
l5(a,a.o)},l5=function(a,b){if(null!=a.Mi)throw Error("WatchDog timer not null");
a.Mi=m5((0,g.z)(a.VK,a),b)},n5=function(a){a.Mi&&(g.w.clearTimeout(a.Mi),a.Mi=null)},g5=function(a){a.g.Vv()||a.Dg||a.g.an(a)},f5=function(a){n5(a);
g.qf(a.tn);a.tn=null;a.i.stop();g.nn(a.ca);if(a.oc){var b=a.oc;a.oc=null;b.abort();b.dispose()}a.ue&&(a.ue=null)},e5=function(a,b){try{a.g.Ny(a,b),a.g.me(4)}catch(c){}},p5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;o5(a,b,function(k){k?c(!0):g.w.setTimeout(function(){p5(a,b,c,d,f)},f)})}},o5=function(a,b,c){var d=new Image;
d.onload=function(){try{q5(d),c(!0)}catch(e){}};
d.onerror=function(){try{q5(d),c(!1)}catch(e){}};
d.onabort=function(){try{q5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{q5(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},q5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},r5=function(a){this.g=a;
this.i=new W4},t5=function(a){var b=s5(a.g,a.cj,"/mail/images/cleardot.gif");
c4(b);p5(b.toString(),5E3,(0,g.z)(a.WB,a),3,2E3);a.me(1)},v5=function(a){var b=a.g.F;
if(null!=b)c5(5),b?(c5(11),u5(a.g,a,!1)):(c5(12),u5(a.g,a,!0));else if(a.Bd=new X4(a,void 0,void 0,void 0),a.Bd.Mg=a.Qp,b=a.g,b=s5(b,b.Jk()?a.Ij:null,a.Rp),c5(5),!g.Md||g.Dc(10))d4(b,"TYPE","xmlhttp"),$4(a.Bd,b,!1,a.Ij,!1);else{d4(b,"TYPE","html");var c=a.Bd;a=!!a.Ij;c.Ph=3;c.Zf=c4(b.clone());k5(c,a)}},w5=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new W4;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Rpa=function(a,b){this.g=a;
this.map=b;this.context=null},x5=function(a){g.sf.call(this,"statevent",a)},y5=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},z5=function(a){g.sf.call(this,"serverreachability",a)},D5=function(a){A5(a);
if(3==a.g){var b=a.qk++,c=a.Ml.clone();g.en(c,"SID",a.l);g.en(c,"RID",b);g.en(c,"TYPE","terminate");B5(a,c);b=new X4(a,a.l,b,void 0);b.Ph=2;b.Zf=c4(c.clone());(new Image).src=b.Zf;b.wi=(0,g.C)();a5(b)}C5(a)},F5=function(a){a.mC(1,0);
a.Ml=s5(a,null,a.Pp);E5(a)},A5=function(a){a.Rf&&(a.Rf.abort(),a.Rf=null);
a.Tb&&(a.Tb.cancel(),a.Tb=null);a.ff&&(g.w.clearTimeout(a.ff),a.ff=null);G5(a);a.yd&&(a.yd.cancel(),a.yd=null);a.Wf&&(g.w.clearTimeout(a.Wf),a.Wf=null)},H5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Rpa(a.UG++,b));2!=a.g&&3!=a.g||E5(a)},E5=function(a){a.yd||a.Wf||(a.Wf=m5((0,g.z)(a.Sy,a),0),a.Kh=0)},K5=function(a,b){if(1==a.g){if(!b){a.qk=Math.floor(1E5*Math.random());
var c=a.qk++,d=new X4(a,"",c,void 0);d.Mg=null;var e=I5(a),f=a.Ml.clone();g.en(f,"RID",c);g.en(f,"CVER","1");B5(a,f);Z4(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?J5(a,b):0==a.i.length||a.yd||J5(a))},J5=function(a,b){if(b)if(6<a.Eg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.qk-1;var d=I5(a)}else c=b.B,d=b.jh;else c=a.qk++,d=I5(a);var e=a.Ml.clone();g.en(e,"SID",a.l);g.en(e,"RID",c);g.en(e,"AID",a.ai);B5(a,e);c=new X4(a,a.l,c,a.Kh+1);c.Mg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;Z4(c,e,d)},B5=function(a,b){if(a.Uc){var c=a.Uc.Cv();
c&&g.Kb(c,function(d,e){g.en(b,e,d)})}},I5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Eg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Eg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},L5=function(a){a.Tb||a.ff||(a.B=1,a.ff=m5((0,g.z)(a.Ry,a),0),a.Dh=0)},N5=function(a){if(a.Tb||a.ff||3<=a.Dh)return!1;
a.B++;a.ff=m5((0,g.z)(a.Ry,a),M5(a,a.Dh));a.Dh++;return!0},u5=function(a,b,c){a.ao=c;
a.Ee=b.tf;a.A||F5(a)},G5=function(a){null!=a.Ig&&(g.w.clearTimeout(a.Ig),a.Ig=null)},M5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},P5=function(a,b){if(2==b||9==b){var c=null;
a.Uc&&(c=null);var d=(0,g.z)(a.WL,a);c||(c=new g.Xm("//www.google.com/images/cleardot.gif"),c4(c));o5(c.toString(),1E4,d)}else c5(2);O5(a,b)},O5=function(a,b){a.g=0;
a.Uc&&a.Uc.Au(b);C5(a);A5(a)},C5=function(a){a.g=0;
a.Ee=-1;if(a.Uc)if(0==a.o.length&&0==a.i.length)a.Uc.bp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Uc.bp(b)}},s5=function(a,b,c){var d=g.fn(c);
if(""!=d.g)b&&g.Zm(d,b+"."+d.g),g.$m(d,d.u);else{var e=window.location;d=Dpa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.pj&&g.Kb(a.pj,function(f,k){g.en(d,k,f)});
g.en(d,"VER",a.Eg);B5(a,d);return d},m5=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},c5=function(a){Q5.dispatchEvent(new x5(Q5,a))},R5=function(){},Spa=function(a,b){this.action=a;
this.params=b||{}},S5=function(a,b){g.G.call(this);
this.g=new g.M(this.DK,0,this);g.H(this,this.g);this.Wc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},T5=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Jo;this.i=new S5(this.pM,this);this.g=null;this.ab=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.J=c||!1},Tpa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.ao,sessionId:a.g.l,arrayId:a.g.ai}},U5=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&K5(a.g),D5(a.g));a.D=0},V5=function(a){return!!a.g&&3==a.g.g},Upa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},W5=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Qg(a)||"";b&&(this.port=":"+b);this.domain=g.Pg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},X5=function(a,b){var c=a.g;
if(g.Ba(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Zg(c+b,{})},Y5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),md:g.Ra(a.u,e)};c&&(a.sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Fq(b,a)},Vpa=function(){var a=Z5;
$5();a6.push(a);b6(a6)},c6=function(a,b){$5();
var c=a6,d=Wpa(a,String(b));0==c.length?Xpa(d):(b6(c),(0,g.B)(c,function(e){e(d)}))},$5=function(){a6||(a6=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",a6,void 0))},Xpa=function(a){var b=(d6+1)%50;
d6=b;e6[b]=a;f6||(f6=49==b)},b6=function(a){var b=e6;
if(b[0]){var c=d6,d=f6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
e6=Array(50);d6=-1;f6=!1}},Wpa=function(a,b){var c=((0,g.C)()-Ypa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g6=function(a){g.O.call(this);
this.B=a;this.g=[]},h6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Zpa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!B4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=h6(a,b[d])||c;return c},$pa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},i6=function(a,b,c,d){g.O.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},k6=function(a){g6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;j6(this);this.info("Initializing with "+z4(this.g))},l6=function(a){if(a.g.length){var b=(0,g.F)(a.g,function(d){return d.id}),c=X5(a.l,"/pairing/get_lounge_token_batch");
Y5(a.l,c,{screen_ids:b.join(",")},(0,g.z)(a.UC,a),(0,g.z)(a.TC,a))}},j6=function(a){var b=x4(J4());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Zpa(a,b)},m6=function(a,b){Lpa((0,g.F)(a.g,w4));
b&&K4()},o6=function(a,b){g.O.call(this);
this.A=b;var c=g.ht("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;n6("Initialized with "+g.Hg(this.g))},p6=function(a,b,c){var d=X5(a.u,"/pairing/get_screen_availability");
Y5(a.u,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},q6=function(a,b){a:if(p4(b)!=p4(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(n6("Updated online screens: "+g.Hg(a.g)),a.g=b,a.N("screenChange"));aqa(a)},r6=function(a){isNaN(a.l)||g.Sp(a.l);
a.l=g.Qp((0,g.z)(a.ds,a),0<a.o&&a.o<(0,g.C)()?2E4:1E4)},n6=function(a){c6("OnlineScreenService",a)},s6=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Kb("Requesting availability of screen w/o lounge token.")});
return b},aqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.gt("yt-remote-online-screen-ids",a.join(","),60):g.it("yt-remote-online-screen-ids")},t6=function(a){g6.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};bqa(this)},v6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Gd();if(k=(c?C4(k,c):null)||C4(k,b)){k.uuid=b;var l=u6(a,k);p6(a.i,l,function(m){e(m?l:null)})}else c?cqa(a,c,(0,g.z)(function(m){var n=u6(this,new u4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));p6(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},w6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},cqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Fq(X5(a.A,"/pairing/get_lounge_token_batch"),e)},x6=function(a){a.g=a.l.Gd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+z4(a.g))},bqa=function(a){y6(a);
a.l=new k6(a.A);a.l.subscribe("screenChange",(0,g.z)(a.dD,a));x6(a);a.o=x4(g.ht("yt-remote-automatic-screen-cache")||[]);y6(a);a.info("Initializing automatic screens: "+z4(a.o));a.i=new o6(a.A,(0,g.z)(a.Gd,a,!0));a.i.subscribe("screenChange",(0,g.z)(function(){this.N("onlineScreenChange")},a))},u6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=C4(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.gt("yt-remote-automatic-screen-cache",(0,g.F)(a.o,w4)));y6(a);a.u[b.uuid]=b.id;g.gt("yt-remote-device-id-map",a.u,31536E3);return b},y6=function(a){a.u=g.ht("yt-remote-device-id-map")||{}},z6=function(a,b,c){g.O.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},A6=function(a,b){c6(a.P,b)},C6=function(a,b){z6.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.z)(this.vM,this);this.u=(0,g.z)(this.gL,this);this.o=g.Qp((0,g.z)(function(){B6(this,null)},this),12E4)},dqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Hg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Fa,(0,g.z)(function(){A6(this,"Failed to send message: getMdxSessionStatus.")},a)):A6(a,"Sending yt message without session: "+g.Hg(b))},B6=function(a,b){g.Sp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.z)(a.bn,a),d=(0,g.z)(a.Jd,a);a.Ov(b,c,d,5)}}else a.Jd(Error("Waiting for session status timed out."))},D6=function(a,b,c){z6.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Fa;this.A=NaN;this.J=(0,g.z)(this.yM,this);this.g=g.Fa},E6=function(a){a.g=a.F.WA(a.H,a.i.label,a.i.friendlyName,(0,g.z)(function(b){this.g=g.Fa;
this.bn(b)},a),(0,g.z)(function(b){this.g=g.Fa;
this.Jd(b)},a))},F6=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}N4()&&(b.env_useStageMdx=1);return g.Xg(b)},G6=function(a,b){z6.call(this,a,b,"ManualSession");
this.g=g.Qp((0,g.z)(this.ci,this,null),150)},H6=function(a,b,c,d){g.O.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.z)(this.MJ,this)},I6=function(a,b){return b?g.Xa(a.l,function(c){return v4(b,c.label)},a):null},J6=function(a){c6("Controller",a)},Z5=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},K6=function(a){return a.u||!!a.l.length||!!a.g},L6=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.z)(a.Qy,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ci(null)):a.N("yt-remote-cast2-session-change",null))},M6=function(a){var b=a.i.VA(),c=a.g&&a.g.i;
a=(0,g.F)(b,function(d){c&&v4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=I6(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},hqa=function(a,b,c,d,e,f,k){eqa()?fqa(b,e,f,k)&&(O6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?P6(a,c):(window.__onGCastApiAvailable=function(l,m){l?P6(a,c):(Q6("Failed to load cast API: "+m),R6(!1),O6(!1),g.it("yt-remote-cast-available"),g.it("yt-remote-cast-receiver"),S6(),c(!1))},d?g.cq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Ppa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?S4():(U4(),R4(gqa.map(Npa))))):N6("Cannot initialize because not running Chrome")},S6=function(){N6("dispose");
var a=T6();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);U6(!1);g.Yp(V6);V6.length=0},W6=function(){return!!g.ht("yt-remote-cast-installed")},X6=function(){var a=g.ht("yt-remote-cast-receiver");
return a?a.friendlyName:null},Y6=function(){N6("clearCurrentReceiver");
g.it("yt-remote-cast-receiver")},Z6=function(){return W6()?T6()?T6().getCastSession():(Q6("getCastSelector: Cast is not initialized."),null):(Q6("getCastSelector: Cast API is not installed!"),null)},a7=function(){W6()?T6()?$6()?(N6("Requesting cast selector."),T6().requestSession()):(N6("Wait for cast API to be ready to request the session."),V6.push(g.Xp("yt-remote-cast2-api-ready",a7))):Q6("requestCastSelector: Cast is not initialized."):Q6("requestCastSelector: Cast API is not installed!")},b7=
function(a,b){$6()?T6().setConnectedScreenStatus(a,b):Q6("setConnectedScreenStatus called before ready.")},eqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.Nw||a},iqa=function(a,b){T6().init(a,b)},fqa=function(a,b,c,d){var e=!1;
T6()||(a=new H6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.gt("yt-remote-cast-available",f);s4("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){N6("onReceiverSelected: "+f.friendlyName);
g.gt("yt-remote-cast-receiver",f);s4("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){N6("onReceiverResumed: "+f.friendlyName);
g.gt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){N6("onSessionChange: "+y4(f));
f||g.it("yt-remote-cast-receiver");s4("yt-remote-cast2-session-change",f)}),g.Ea("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
N6("cloudview.createSingleton_: "+e);return e},T6=function(){return g.x("yt.mdx.remote.cloudview.instance_")},P6=function(a,b){R6(!0);
O6(!1);iqa(a,function(c){c?(U6(!0),g.$p("yt-remote-cast2-api-ready")):(Q6("Failed to initialize cast API."),R6(!1),g.it("yt-remote-cast-available"),g.it("yt-remote-cast-receiver"),S6());b(c)})},N6=function(a){c6("cloudview",a)},Q6=function(a){c6("cloudview",a)},R6=function(a){N6("setCastInstalled_ "+a);
g.gt("yt-remote-cast-installed",a)},$6=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},U6=function(a){N6("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},O6=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},c7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Ge=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},d7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ge=!1;a.hasNext=!1;a.B=0;a.A=(0,g.C)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},e7=function(a){return 1==a.playerState?((0,g.C)()-a.A)/1E3:0},f7=function(a,b){a.B=b;
a.A=(0,g.C)()},g7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},h7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&d7(a)},i7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Ge;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},l7=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.A=[];this.u=new r4;this.l=this.i=null;this.F=(0,g.z)(this.EH,this);this.B=(0,g.z)(this.rk,this);this.D=(0,g.z)(this.DH,this);this.H=(0,g.z)(this.QH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ht,this),j7(this))):c=3;0!=c&&(b?this.ht(c):g.Qp((0,g.z)(function(){this.ht(c)},this),0));
var d=Z6();d&&k7(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},m7=function(a){return new c7(a.o.getPlayerContextData())},j7=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Ra(this.JJ,b),this))},a)},n7=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},o7=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},q7=function(a,b,c){var d=m7(a);
f7(d,c);-1E3!=d.playerState&&(d.playerState=b);p7(a,d)},r7=function(a,b,c){a.o.sendMessage(b,c)},p7=function(a,b){n7(a);
a.o.setPlayerContextData(i7(b));j7(a)},k7=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.rk(null));
a.l=b;a.l&&(c6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.rk(a.l.media[0]))},s7=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=m7(a);b.contentId!=d.videoId&&c6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;f7(d,a.i.getEstimatedTime());p7(a,d)}else c6("CP","No cast media video. Ignoring state update.")},t7=function(a,b,c){return(0,g.z)(function(d){this.Kb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Kb("Retrying "+b+" using MDx browser channel."),r7(this,b,c))},a)},u7=function(a,b,c){g.O.call(this);
this.u=NaN;this.M=!1;this.H=this.F=this.J=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Pa=this.g=null;this.na=a;this.O.push(g.Er(window,"beforeunload",(0,g.z)(this.NC,this)));this.i=[];this.Pa=new c7;this.V=b.id;this.g=jqa(this,c);this.g.subscribe("handlerOpened",this.IH,this);this.g.subscribe("handlerClosed",this.FH,this);this.g.subscribe("handlerError",this.GH,this);this.g.subscribe("handlerMessage",this.HH,this);Upa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Pa.videoId;
g.jt()&&g.gt("yt-remote-session-video-id",d)},this)},v7=function(a){c6("conn",a)},jqa=function(a,b){return new T5(X5(a.na,"/bc"),b)},w7=function(a,b){a.N("proxyStateChange",b)},kqa=function(a){a.u=g.Qp((0,g.z)(function(){v7("Connecting timeout");
this.A(1)},a),2E4)},x7=function(a){g.Sp(a.u);
a.u=NaN},y7=function(a){g.Sp(a.P);
a.P=NaN},lqa=function(a){z7(a);
a.J=g.Qp((0,g.z)(function(){A7(this,"getNowPlaying")},a),2E4)},z7=function(a){g.Sp(a.J);
a.J=NaN},C7=function(a,b){b&&(x7(a),y7(a));
b==(V5(a.g)&&isNaN(a.u))?b&&(w7(a,1),A7(a,"getSubtitlesTrack")):b?(a.R()&&a.Pa.reset(),w7(a,1),A7(a,"getNowPlaying"),B7(a)):a.A(1)},mqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.Xb(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.N("remotePlayerChange"))},D7=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;h7(a.Pa,c,d);a.N("remoteQueueChange")},nqa=function(a,b){b.params=b.params||{};
D7(a,b);E7(a,b);a.N("autoplayDismissed")},E7=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
f7(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?lqa(a):z7(a);a.N("remotePlayerChange")},oqa=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);f7(a.Pa,isNaN(c)?0:c);a.N("remotePlayerChange")}},pqa=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.N("remotePlayerChange")},qqa=function(a,b){a.B=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},rqa=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Ge="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.N("previousNextChange")},B7=function(a){g.Sp(a.H);
a.H=g.Qp((0,g.z)(a.A,a,1),864E5)},A7=function(a,b,c){c?v7("Sending: action="+b+", params="+g.Hg(c)):v7("Sending: action="+b);
a.g.sendMessage(b,c)},F7=function(a){g6.call(this,"ScreenServiceProxy");
this.Fc=a;this.i=[];this.i.push(this.Fc.$_s("screenChange",(0,g.z)(this.tM,this)));this.i.push(this.Fc.$_s("onlineScreenChange",(0,g.z)(this.nJ,this)))},wqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Ip("MDX_CONFIG")||b;Jpa();H4();G7||(G7=new W5(b?b.loungeApiHost:void 0),N4()&&(G7.g="/api/loungedev"));H7||(H7=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",H7,void 0));sqa();var c=I7();if(!c){var d=new t6(G7);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=I7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);hqa(a,d,function(m){m?J7()&&b7(J7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){s4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ea("yt.mdx.remote.initialized_",!0,void 0),K7("Initializing: "+g.Hg(b)),L7.push(g.Xp("yt-remote-cast2-availability-change",function(){s4("yt-remote-receiver-availability-change")})),L7.push(g.Xp("yt-remote-cast2-receiver-selected",function(){M7(null);
s4("yt-remote-auto-connect","cast-selector-receiver")})),L7.push(g.Xp("yt-remote-cast2-receiver-resumed",function(){s4("yt-remote-receiver-resumed","cast-selector-receiver")})),L7.push(g.Xp("yt-remote-cast2-session-change",tqa)),L7.push(g.Xp("yt-remote-connection-change",function(m){m?b7(J7(),"YouTube TV"):N7()||(b7(null,null),Y6())})),a=O7(),b.isAuto&&(a.id+="#dial"),g.wq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),K7(" -- with channel params: "+
g.Hg(a)),uqa(a),c.start(),J7()||vqa())},xqa=function(){var a=P7();
W6()&&g.ht("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},P7=function(){var a=I7().Fc.$_gos();
var b=Q7();b&&R7()&&(B4(a,b)||a.push(b));return Ipa(a)},S7=function(){var a=yqa();
!a&&W6()&&X6()&&(a={key:"cast-selector-receiver",name:X6()});return a},yqa=function(){var a=P7(),b=Q7();
b||(b=N7());return g.Xa(a,function(c){return b&&v4(b,c.key)?!0:!1})},Q7=function(){var a=J7();
if(!a)return null;var b=I7().Gd();return C4(b,a)},tqa=function(a){K7("remote.onCastSessionChange_: "+y4(a));
if(a){var b=Q7();b&&b.id==a.id?b7(b.id,"YouTube TV"):(b&&T7(),U7(a,1))}else R7()&&T7()},T7=function(){$6()?T6().stopSession():Q6("stopSession called before API ready.");
var a=R7();a&&(a.disconnect(1),V7(null))},W7=function(){var a=R7();
return!!a&&3!=a.getProxyState()},K7=function(a){c6("remote",a)},I7=function(){if(!X7){var a=g.x("yt.mdx.remote.screenService_");
X7=a?new F7(a):null}return X7},J7=function(){return g.x("yt.mdx.remote.currentScreenId_")},Y7=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},Z7=function(){return g.x("yt.mdx.remote.connectData_")},M7=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},R7=function(){return g.x("yt.mdx.remote.connection_")},V7=function(a){var b=R7();
M7(null);a||Y7("");g.Ea("yt.mdx.remote.connection_",a,void 0);H7&&((0,g.B)(H7,function(c){c(a)}),H7.length=0);
b&&!a?s4("yt-remote-connection-change",!1):!b&&a&&s4("yt-remote-connection-change",!0)},N7=function(){var a=g.jt();
if(!a)return null;var b=I7().Gd();return C4(b,a)},U7=function(a,b){Q7()&&Q7();
Y7(a.id);var c=new u7(G7,a,O7());c.connect(b,Z7());c.subscribe("beforeDisconnect",function(d){s4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){R7()&&V7(null)});
V7(c)},vqa=function(){var a=N7();
a?(K7("Resume connection to: "+y4(a)),U7(a,0)):(L4(),Y6(),K7("Skipping connecting because no session screen found."))},sqa=function(){var a=O7();
if(g.Xb(a)){a=G4();var b=g.ht("yt-remote-session-name")||"",c=g.ht("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},O7=function(){return g.x("yt.mdx.remote.channelParams_")||{}},uqa=function(a){a?(g.gt("yt-remote-session-app",a.app),g.gt("yt-remote-session-name",a.name)):(g.it("yt-remote-session-app"),g.it("yt-remote-session-name"));
g.Ea("yt.mdx.remote.channelParams_",a,void 0)},$7=function(a,b,c){g.G.call(this);
this.u=a;this.i=b;this.l=new g.Rr(this);g.H(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.CI);this.l.K(b,"captionschanged",this.CH);this.l.K(b,"captionssettingschanged",this.iA);this.l.K(b,"videoplayerreset",this.cn);this.l.K(b,"mdxautoplaycancel",this.VB);this.O=this.l.K(b,"onVolumeChange",this.By);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.My,this);c.subscribe("remotePlayerChange",this.vk,this);c.subscribe("remoteQueueChange",this.cn,this);c.subscribe("autoplayUpNext",this.ny,
this);c.subscribe("previousNextChange",this.Jy,this);c.subscribe("nowAutoplaying",this.Fy,this);c.subscribe("autoplayDismissed",this.my,this);this.suggestion=null;this.F=new g.FC(64);this.o=new g.M(this.gA,500,this);g.H(this,this.o);this.A=new g.M(this.hA,1E3,this);g.H(this,this.A);this.J=new V4(this.eM,0,this);g.H(this,this.J);this.B={};this.P=new g.M(this.HA,1E3,this);g.H(this,this.P);this.H=new g.El(this.iF,1E3,this);g.H(this,this.H);this.M=g.Fa;this.iA();this.cn();this.vk()},a8=function(a,b){a.u.pd(b,
a.i.getVideoData().lengthSeconds)},c8=function(a){a8(a,0);
a.o.stop();b8(a,new g.FC(64))},e8=function(a,b){if(d8(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.Wz(a.i.getVideoData(1).videoId,c);a.B=m7(a.g).g}},f8=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Vh,o4(c));b8(a,new g.FC(1))},g8=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{OP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},d8=function(a){return m7(a.g).videoId==a.i.getVideoData(1).videoId},b8=function(a,b){a.A.stop();
var c=a.F;if(!g.LC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.zJ(a.i,d);a.F=b;h8(a.u,c,b)}},j8=function(a){g.T.call(this,{C:"div",
G:"ytp-remote",I:[{C:"div",G:"ytp-remote-display-status",I:[{C:"div",G:"ytp-remote-display-status-icon",I:[g.KO()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.uP(this,250);g.H(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);i8(this,g.vJ(a))},i8=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.KM("Error on $RECEIVER_NAME",c):g.MC(b)||g.U(b,4)?g.KM("Playing on $RECEIVER_NAME",c):g.KM("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},k8=function(a,b){g.cT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.J);this.K(a,"presentingplayerstatechange",this.J);this.J()},l8=function(a){g.$J.call(this,a);
this.i={key:A4(),name:"This computer"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.ek=new g.FC(64);this.D=0;this.rm=-1;if(!g.Ly(g.V(this.player))){a=this.player;var b=g.dC(a);b&&(b=b.Mm())&&(b=new k8(a,b),g.H(this,b));b=new j8(a);g.H(this,b);g.MJ(a,b.element,4)}},h8=function(a,b,c){a.ek=c;
a.player.N("presentingplayerstatechange",new g.QC(c,b))},m8=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)T7();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Vh,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=o4(d))&&(c.locationInfo=d);d=c}else d=null;K7("Connecting to: "+g.Hg(b));"cast-selector-receiver"==b.key?
(M7(d||null),$6()?T6().setLaunchParams(d||null):Q6("setLaunchParams called before ready.")):!d&&W7()&&J7()==b.key?s4("yt-remote-connection-change",!0):(T7(),M7(d||null),d=I7().Gd(),(d=C4(d,b.key))&&U7(d,1))}},xpa=/^https?$/i,zqa=["POST",
"PUT"];g.A(m4,g.Qf);g.h=m4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.M?e4(this.M):e4(g.hY);this.P=this.M?this.M.getOptions():g.hY.getOptions();this.g.onreadystatechange=(0,g.z)(this.Xv,this);try{b4(f4(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){b4(f4(this,"Error opening Xhr: "+f.message));j4(this,f);return}a=c||
"";var e=this.headers.clone();d&&upa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Fd(),vpa);c=g.w.FormData&&a instanceof g.w.FormData;!g.$a(zqa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Y&&(this.g.responseType=this.Y);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{g4(this),0<this.A&&(this.J=wpa(this.g),b4(f4(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.J)),this.J?(this.g.timeout=this.A,this.g.ontimeout=(0,g.z)(this.Yv,this)):this.B=g.Dg(this.Yv,this.A,this)),b4(f4(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){b4(f4(this,"Send error: "+f.message)),j4(this,f)}};
g.h.Yv=function(){"undefined"!=typeof g.LX&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,f4(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(f4(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),i4(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),i4(this,!0));m4.Ha.T.call(this)};
g.h.Xv=function(){this.ea()||(this.V||this.D||this.o?l4(this):this.LJ())};
g.h.LJ=function(){l4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<k4(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var j5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},i5={"'":"\\'"},Aqa={};g.h=r4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.cma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.uc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var Gpa={SM:"atp",dP:"ska",SO:"que",sO:"mus",cP:"sus",JN:"dsp",ZO:"seq"};t4.prototype.Sf=function(){var a=new t4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var M4,F4="",T4=O4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Opa=O4("loadCastFramework")||O4("loadCastApplicationFramework"),gqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(V4,g.G);g.h=V4.prototype;g.h.JC=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.C)()+this.Wc:this.za=g.Dg(this.u,this.Wc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();V4.Ha.T.call(this)};
g.h.KC=function(){this.l?(this.za=g.Dg(this.u,this.l-(0,g.C)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};W4.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
W4.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=X4.prototype;g.h.Mg=null;g.h.se=!1;g.h.Mi=null;g.h.Zs=null;g.h.wi=null;g.h.Ph=null;g.h.Zf=null;g.h.rg=null;g.h.jh=null;g.h.oc=null;g.h.Rk=0;g.h.ue=null;g.h.eo=null;g.h.ag=null;g.h.Jj=-1;g.h.Iz=!0;g.h.Dg=!1;g.h.Sp=0;g.h.tn=null;var d5={},b5={};g.h=X4.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.tL=function(a){a=a.target;var b=this.tn;b&&3==k4(a)?b.Fj():this.RA(a)};
g.h.RA=function(a){try{if(a==this.oc)a:{var b=k4(this.oc),c=this.oc.u,d=this.oc.getStatus();if(g.Md&&!g.Dc(10)||g.Od&&!g.Cc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.yh&&!n4(this.oc))break a;this.Dg||4!=b||7==c||(8==c||0>=d?this.g.me(3):this.g.me(2));n5(this);var e=this.oc.getStatus();this.Jj=e;var f=n4(this.oc);(this.se=200==e)?(4==b&&f5(this),this.u?(h5(this,b,f),g.yh&&this.se&&3==b&&(this.ca.da(this.i,"tick",this.pL),this.i.start())):e5(this,f),this.se&&!this.Dg&&(4==b?this.g.an(this):(this.se=
!1,a5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ag=3,c5(13)):(this.ag=0,c5(14)),f5(this),g5(this))}}catch(k){this.oc&&n4(this.oc)}finally{}};
g.h.pL=function(){var a=k4(this.oc),b=n4(this.oc);this.Rk<b.length&&(n5(this),h5(this,a,b),this.se&&4!=a&&a5(this))};
g.h.LK=function(a){m5((0,g.z)(this.KK,this,a),0)};
g.h.KK=function(a){this.Dg||(n5(this),e5(this,a),a5(this))};
g.h.Ty=function(a){m5((0,g.z)(this.JK,this,a),0)};
g.h.JK=function(a){this.Dg||(f5(this),this.se=a,this.g.an(this),this.g.me(4))};
g.h.cancel=function(){this.Dg=!0;f5(this)};
g.h.VK=function(){this.Mi=null;var a=(0,g.C)();0<=a-this.Zs?(2!=this.Ph&&this.g.me(3),f5(this),this.ag=2,c5(18),g5(this)):l5(this,this.Zs-a)};
g.h.getLastError=function(){return this.ag};g.h=r5.prototype;g.h.Qp=null;g.h.Bd=null;g.h.un=!1;g.h.Wv=null;g.h.Kl=null;g.h.Fq=null;g.h.Rp=null;g.h.Vd=null;g.h.tf=-1;g.h.Ij=null;g.h.cj=null;g.h.connect=function(a){this.Rp=a;a=s5(this.g,null,this.Rp);c5(3);this.Wv=(0,g.C)();var b=this.g.D;null!=b?(this.Ij=b[0],(this.cj=b[1])?(this.Vd=1,t5(this)):(this.Vd=2,v5(this))):(d4(a,"MODE","init"),this.Bd=new X4(this,void 0,void 0,void 0),this.Bd.Mg=this.Qp,$4(this.Bd,a,!1,null,!0),this.Vd=0)};
g.h.WB=function(a){if(a)this.Vd=2,v5(this);else{c5(4);var b=this.g;b.Ee=b.Rf.tf;P5(b,9)}a&&this.me(2)};
g.h.pp=function(a){return this.g.pp(a)};
g.h.abort=function(){this.Bd&&(this.Bd.cancel(),this.Bd=null);this.tf=-1};
g.h.Vv=function(){return!1};
g.h.Ny=function(a,b){this.tf=a.Jj;if(0==this.Vd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ee=this.tf;P5(c,2);return}this.Ij=c[0];this.cj=c[1]}else c=this.g,c.Ee=this.tf,P5(c,2);else if(2==this.Vd)if(this.un)c5(7),this.Fq=(0,g.C)();else if("11111"==b){if(c5(6),this.un=!0,this.Kl=(0,g.C)(),c=this.Kl-this.Wv,!g.Md||g.Dc(10)||500>c)this.tf=200,this.Bd.cancel(),c5(12),u5(this.g,this,!0)}else c5(8),this.Kl=this.Fq=(0,g.C)(),this.un=!1};
g.h.an=function(){this.tf=this.Bd.Jj;if(this.Bd.se)0==this.Vd?this.cj?(this.Vd=1,t5(this)):(this.Vd=2,v5(this)):2==this.Vd&&((!g.Md||g.Dc(10)?!this.un:200>this.Fq-this.Kl)?(c5(11),u5(this.g,this,!1)):(c5(12),u5(this.g,this,!0)));else{0==this.Vd?c5(9):2==this.Vd&&c5(10);var a=this.g;this.Bd.getLastError();a.Ee=this.tf;P5(a,2)}};
g.h.Jk=function(){return this.g.Jk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.me=function(a){this.g.me(a)};g.h=w5.prototype;g.h.pj=null;g.h.yd=null;g.h.Tb=null;g.h.Pp=null;g.h.Ml=null;g.h.ru=null;g.h.Vl=null;g.h.qk=0;g.h.UG=0;g.h.Uc=null;g.h.Wf=null;g.h.ff=null;g.h.Ig=null;g.h.Rf=null;g.h.ao=null;g.h.ai=-1;g.h.Dw=-1;g.h.Ee=-1;g.h.Kh=0;g.h.Dh=0;g.h.Eg=8;var Q5=new g.Qf;g.A(x5,g.sf);g.A(y5,g.sf);g.A(z5,g.sf);g.h=w5.prototype;g.h.connect=function(a,b,c,d,e){c5(0);this.Pp=b;this.pj=c||{};d&&g.Ba(e)&&(this.pj.OSID=d,this.pj.OAID=e);this.A?(m5((0,g.z)(this.Ju,this,a),100),F5(this)):this.Ju(a)};
g.h.Ju=function(a){this.Rf=new r5(this);this.Rf.Qp=null;this.Rf.i=this.u;this.Rf.connect(a)};
g.h.Vv=function(){return 0==this.g};
g.h.Sy=function(a){this.Wf=null;K5(this,a)};
g.h.Ry=function(){this.ff=null;this.Tb=new X4(this,this.l,"rpc",this.B);this.Tb.Mg=null;this.Tb.Sp=0;var a=this.ru.clone();g.en(a,"RID","rpc");g.en(a,"SID",this.l);g.en(a,"CI",this.ao?"0":"1");g.en(a,"AID",this.ai);B5(this,a);if(!g.Md||g.Dc(10))g.en(a,"TYPE","xmlhttp"),$4(this.Tb,a,!0,this.Vl,!1);else{g.en(a,"TYPE","html");var b=this.Tb,c=!!this.Vl;b.Ph=3;b.Zf=c4(a.clone());k5(b,c)}};
g.h.Ny=function(a,b){if(0!=this.g&&(this.Tb==a||this.yd==a))if(this.Ee=a.Jj,this.yd==a&&3==this.g)if(7<this.Eg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ja(c)&&3==c.length)if(0==c[0])a:{if(!this.ff){if(this.Tb)if(this.Tb.wi+3E3<this.yd.wi)G5(this),this.Tb.cancel(),this.Tb=null;else break a;N5(this);c5(19)}}else this.Dw=c[1],0<this.Dw-this.ai&&37500>c[2]&&this.ao&&0==this.Dh&&!this.Ig&&(this.Ig=m5((0,g.z)(this.xH,this),6E3));else P5(this,11)}else b!=Aqa.pN.g&&P5(this,11);else if(this.Tb==a&&
G5(this),!g.wb(b)){c=this.u.parse(b);g.Ja(c);for(var d=0;d<c.length;d++){var e=c[d];this.ai=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Vl=e[2],e=e[3],null!=e?this.Eg=e:this.Eg=6,this.g=3,this.Uc&&this.Uc.Cu(),this.ru=s5(this,this.Jk()?this.Vl:null,this.Pp),L5(this)):"stop"==e[0]&&P5(this,7):3==this.g&&("stop"==e[0]?P5(this,7):"noop"!=e[0]&&this.Uc&&this.Uc.Bu(e),this.Dh=0)}}};
g.h.xH=function(){null!=this.Ig&&(this.Ig=null,this.Tb.cancel(),this.Tb=null,N5(this),c5(20))};
g.h.an=function(a){if(this.Tb==a){G5(this);this.Tb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.Ee=a.Jj;if(0!=this.g)if(a.se)1==b?(b=(0,g.C)()-a.wi,Q5.dispatchEvent(new y5(Q5,a.jh?a.jh.length:0,b,this.Kh)),E5(this),this.o.length=0):L5(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ee)){if(d=1==b)this.yd||this.Wf||1==this.g||2<=this.Kh?d=!1:(this.Wf=m5((0,g.z)(this.Sy,this,a),M5(this,this.Kh)),this.Kh++,d=!0);d=!(d||2==b&&N5(this))}if(d)switch(c){case 1:P5(this,
5);break;case 4:P5(this,10);break;case 3:P5(this,6);break;case 7:P5(this,12);break;default:P5(this,2)}}};
g.h.mC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.WL=function(a){a?c5(2):(c5(1),O5(this,8))};
g.h.pp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new m4;a.R=!1;return a};
g.h.isActive=function(){return!!this.Uc&&this.Uc.isActive(this)};
g.h.me=function(a){Q5.dispatchEvent(new z5(Q5,a))};
g.h.Jk=function(){return!(!g.Md||g.Dc(10))};
g.h=R5.prototype;g.h.Cu=function(){};
g.h.Bu=function(){};
g.h.Au=function(){};
g.h.bp=function(){};
g.h.Cv=function(){return{}};
g.h.isActive=function(){return!0};g.A(S5,g.G);g.h=S5.prototype;g.h.DK=function(){this.Wc=Math.min(3E5,2*this.Wc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Wc+15E3*Math.random();g.oo(this.g,a);this.i=(0,g.C)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Wc=5E3};g.A(T5,R5);g.h=T5.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Af=function(a){return this.l.Ng(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.ab||(this.ab=!0,g.qf(this.l),U5(this),g.qf(this.i),this.i=null)};
g.h.ea=function(){return this.ab};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new w5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.g;e&&(e.Uc=null);d.Uc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ai):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):V5(this)&&H5(this.g,c)};
g.h.Cu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)H5(this.g,a[b])}this.N("handlerOpened")};
g.h.Au=function(a){var b=2==a&&401==this.g.Ee;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.bp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.Cv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.Bu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),D5(this.g)):this.N("handlerMessage",new Spa(a[0],a[1]))};
g.h.pM=function(){this.i.isActive();var a=this.g,b=0;a.Tb&&b++;a.yd&&b++;0!=b||this.connect(this.u,this.o)};W5.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
W5.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
W5.prototype.u=function(a){a(Error("request timed out"))};var Ypa=(0,g.C)(),a6=null,e6=Array(50),d6=-1,f6=!1;g.A(g6,g.O);g6.prototype.Gd=function(){return this.g};
g6.prototype.contains=function(a){return!!B4(this.g,a)};
g6.prototype.get=function(a){return a?C4(this.g,a):null};
g6.prototype.info=function(a){c6(this.B,a)};g.A(i6,g.O);var n8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=i6.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.UA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Sp(this.za),this.za=NaN)};
g.h.T=function(){this.stop();i6.Ha.T.call(this)};
g.h.UA=function(){this.za=NaN;this.g=g.Fq(X5(this.A,"/pairing/get_screen"),{method:"POST",sb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.z)(this.rM,this),onError:(0,g.z)(this.qM,this),md:(0,g.z)(this.sM,this)})};
g.h.rM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new u4(c))};
g.h.qM=function(a){this.g=null;a.status&&404==a.status?this.i>=n8.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=n8[this.i],this.za=g.Qp((0,g.z)(this.UA,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.sM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(k6,g6);g.h=k6.prototype;g.h.start=function(){j6(this)&&this.N("screenChange");!g.ht("yt-remote-lounge-token-expiration")&&l6(this);g.Sp(this.i);this.i=g.Qp((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){j6(this);h6(this,a);m6(this,!1);this.N("screenChange");b(a);a.token||l6(this)};
g.h.remove=function(a,b){var c=j6(this);$pa(this,a)&&(m6(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Wn=function(a,b,c,d){var e=j6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,m6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.Sp(this.i);k6.Ha.T.call(this)};
g.h.UC=function(a){j6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}m6(this,!b);b&&c6(this.B,"Missed "+b+" lounge tokens.")};
g.h.TC=function(a){c6(this.B,"Requesting lounge tokens failed: "+a)};g.A(o6,g.O);g.h=o6.prototype;g.h.start=function(){var a=parseInt(g.ht("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.C)()-144E5<a?0:a)?r6(this):(this.o=(0,g.C)()+3E5,g.gt("yt-remote-fast-check-period",this.o),this.ds())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){n6("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!C4(a,d)},this);
q6(this,b)};
g.h.T=function(){g.Sp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);o6.Ha.T.call(this)};
g.h.ds=function(){g.Sp(this.l);this.l=NaN;this.i&&this.i.abort();var a=s6(this);if(p4(a)){var b=X5(this.u,"/pairing/get_screen_availability");this.i=Y5(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.z)(this.hK,this,a),(0,g.z)(this.gK,this))}else q6(this,{}),r6(this)};
g.h.hK=function(a,b){this.i=null;var c=g.Rb(s6(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;q6(this,d);r6(this)}else this.Kb("Changing Screen set during request."),this.ds()};
g.h.gK=function(a){this.Kb("Screen availability failed: "+a);this.i=null;r6(this)};
g.h.Kb=function(a){c6("OnlineScreenService",a)};g.A(t6,g6);g.h=t6.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Wn=function(a,b,c,d){this.l.contains(a)?this.l.Wn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c6(this.B,a),d(Error(a)))};
g.h.Gd=function(a){return a?this.g:g.fb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.VA=function(){return(0,g.Yd)(this.Gd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.WA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new i6(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(k){g.qf(f);d(u6(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.z)(f.stop,f)};
g.h.uM=function(a,b,c,d){g.Fq(X5(this.A,"/pairing/get_screen"),{method:"POST",sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var k=new u4(f.screen||{});if(!k.name||w6(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);w6(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(u6(this,k))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
md:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.qf(this.l);g.qf(this.i);t6.Ha.T.call(this)};
g.h.dD=function(){x6(this);this.N("screenChange");this.i.update()};
t6.prototype.dispose=t6.prototype.dispose;g.A(z6,g.O);g.h=z6.prototype;g.h.bn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Jd=function(a){this.ea()||(a&&A6(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){c6(this.P,a)};
g.h.YA=function(){return null};
g.h.us=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){A6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.us("");z6.Ha.T.call(this)};g.A(C6,z6);g.h=C6.prototype;g.h.ts=function(a){if(this.g){if(this.g==a)return;A6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);dqa(this)};
g.h.ci=function(a){this.info("launchWithParams no-op for Cast: "+g.Hg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.Jd()},this),(0,g.z)(function(){this.Jd(Error("Failed to stop receiver app."))},this)):this.Jd(Error("Stopping cast device witout session."))};
g.h.us=g.Fa;g.h.T=function(){this.info("disposeInternal");g.Sp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;C6.Ha.T.call(this)};
g.h.gL=function(a,b){if(!this.ea())if(b){var c=q4(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Hg(c));switch(d){case "mdxSessionStatus":B6(this,c.screenId);break;default:A6(this,"Unknown youtube message: "+d)}}else A6(this,"Unable to parse message.")}else A6(this,"No data in message.")};
g.h.Ov=function(a,b,c,d){v6(this.F,this.i.label,a,this.i.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(A6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Qp((0,g.z)(this.Ov,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.YA=function(){return this.g};
g.h.vM=function(a){this.ea()||a||(A6(this,"Cast session died."),this.Jd())};g.A(D6,z6);g.h=D6.prototype;g.h.ts=function(a){this.o=a;this.o.addUpdateListener(this.J)};
g.h.ci=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Fa;g.Sp(this.A);this.o?this.o.stop((0,g.z)(this.Jd,this,null),(0,g.z)(this.Jd,this,"Failed to stop DIAL device.")):this.Jd()};
g.h.T=function(){this.g();this.g=g.Fa;g.Sp(this.A);this.o&&this.o.removeUpdateListener(this.J);this.o=null;D6.Ha.T.call(this)};
g.h.yM=function(a){this.ea()||a||(A6(this,"DIAL session died."),this.g(),this.g=g.Fa,this.Jd())};
g.h.hq=function(a){this.H=A4();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,F6(this));a(b);E6(this)}else this.B=(0,g.z)(function(){g.Sp(this.A);this.B=g.Fa;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,F6(this));a(c);E6(this)},this),this.A=g.Qp((0,g.z)(function(){this.B()},this),100)};
g.h.yD=function(a,b,c){v6(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.z)(function(d){d&&d.token?(this.bn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.hq(b,c)},this),(0,g.z)(function(d){A6(this,"Failed to get DIAL screen: "+d);
this.hq(b,c)},this))};g.A(G6,z6);G6.prototype.stop=function(){this.Jd()};
G6.prototype.ts=g.Fa;G6.prototype.ci=function(){g.Sp(this.g);this.g=NaN;var a=C4(this.F.Gd(),this.i.label);a?this.bn(a):this.Jd(Error("No such screen"))};
G6.prototype.T=function(){g.Sp(this.g);this.g=NaN;G6.Ha.T.call(this)};g.A(H6,g.O);g.h=H6.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.z)(this.Py,this),(0,g.z)(this.QJ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.YH,this);chrome.cast.initialize(c,(0,g.z)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),Vpa(),this.i.subscribe("onlineScreenChange",(0,g.z)(this.XA,this)),this.l=M6(this),chrome.cast.setCustomReceivers(this.l,g.Fa,(0,g.z)(function(f){this.Kb("Failed to set initial custom receivers: "+g.Hg(f))},this)),this.N("yt-remote-cast2-availability-change",K6(this)),b(!0))},this),(0,g.z)(function(f){this.Kb("Failed to initialize API: "+g.Hg(f));
b(!1)},this))};
g.h.LL=function(a,b){J6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)J6("Unsetting old screen status: "+this.g.i.friendlyName),L6(this,null)}if(a&&b){if(!this.g){c=C4(this.i.Gd(),a);if(!c){J6("setConnectedScreenStatus: Unknown screen.");return}var d=I6(this,c);d||(J6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Fa,(0,g.z)(function(e){this.Kb("Failed to set initial custom receivers: "+g.Hg(e))},this)));
J6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);L6(this,new G6(this.i,d),!0)}this.g.us(b)}else J6("setConnectedScreenStatus: no screen.")};
g.h.ML=function(a){this.ea()?this.Kb("Setting connection data on disposed cast v2"):this.g?this.g.ci(a):this.Kb("Setting connection data without a session")};
g.h.xM=function(){this.ea()?this.Kb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),L6(this,null)):J6("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.Py,this),(0,g.z)(this.mK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.z)(this.XA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.x("yt.mdx.remote.debug.handlers_")||[],Z5);g.qf(this.g);H6.Ha.T.call(this)};
g.h.Kb=function(a){c6("Controller",a)};
g.h.Qy=function(a,b){this.g==a&&(b||L6(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.MJ=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),J6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)J6("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{J6("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:L6(this,
new G6(this.i,a));break;case chrome.cast.ReceiverType.DIAL:L6(this,new D6(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:L6(this,new C6(this.i,a));break;default:this.Kb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Kb("Stopping receiver w/o session: "+a.friendlyName)}else this.Kb("onReceiverAction_ called without receiver.")};
g.h.YH=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Kb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Kb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return J6("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Kb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);L6(this,new D6(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.yD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.z)(b.hq,b))};
g.h.Py=function(a){if(!this.ea()){J6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)J6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),L6(this,new C6(this.i,b),!0);else{this.Kb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=C4(this.i.Gd(),c.label);d&&v4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(J6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new C6(this.i,b),this.g.subscribe("sessionScreen",(0,g.z)(this.Qy,this,this.g)),this.g.ci(null));this.g.ts(a)}}};
g.h.wM=function(){return this.g?this.g.YA():null};
g.h.mK=function(a){this.ea()||(this.Kb("Failed to estabilish a session: "+g.Hg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&L6(this,null))};
g.h.QJ=function(a){J6("Receiver availability updated: "+a);if(!this.ea()){var b=K6(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;K6(this)!=b&&this.N("yt-remote-cast2-availability-change",K6(this))}};
g.h.XA=function(){this.ea()||(this.l=M6(this),J6("Updating custom receivers: "+g.Hg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Fa,(0,g.z)(function(){this.Kb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",K6(this)))};
H6.prototype.setLaunchParams=H6.prototype.ML;H6.prototype.setConnectedScreenStatus=H6.prototype.LL;H6.prototype.stopSession=H6.prototype.xM;H6.prototype.getCastSession=H6.prototype.wM;H6.prototype.requestSession=H6.prototype.requestSession;H6.prototype.init=H6.prototype.init;H6.prototype.dispose=H6.prototype.dispose;var V6=[];c7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";d7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ge=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
c7.prototype.isAdPlaying=function(){return 1081==this.playerState};
c7.prototype.getDuration=function(){return this.u?this.D+e7(this):this.D};
c7.prototype.clone=function(){return new c7(i7(this))};g.A(l7,g.O);g.h=l7.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Fa,t7(this,"play")):r7(this,"play"),q7(this,1,g7(m7(this))),this.N("remotePlayerChange")):o7(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Fa,t7(this,"pause")):r7(this,"pause"),q7(this,2,g7(m7(this))),this.N("remotePlayerChange")):o7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=m7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Fa,t7(this,"seekTo",{newTime:a}))}else r7(this,"seekTo",{newTime:a});q7(this,3,a);this.N("remotePlayerChange")}else o7(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Fa,t7(this,"stopVideo")):r7(this,"stopVideo");var a=m7(this);a.index=-1;a.videoId="";d7(a);p7(this,a);this.N("remotePlayerChange")}else o7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=m7(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.z)(function(){c6("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Kb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.z)(function(){c6("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Kb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);r7(this,"setVolume",e)}c.muted=b;c.volume=a;p7(this,c)}else o7(this,g.Ra(this.setVolume,a,b))};
g.h.Wz=function(a,b){if(1==this.g){var c=m7(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Hg(b.style),g.ec(d,c.g));r7(this,"setSubtitlesTrack",d);p7(this,c)}else o7(this,g.Ra(this.Wz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){r7(this,"setAudioTrack",{videoId:a,audioTrackId:b.ob.id});var c=m7(this);c.audioTrackId=b.ob.id;p7(this,c)}else o7(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=m7(this);c=c||0;var m={videoId:a,currentIndex:c};h7(l,a,c);g.Ba(b)&&(f7(l,b),m.currentTime=b);g.Ba(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Hg(k));r7(this,"setPlaylist",m);d||p7(this,l)};
g.h.kn=function(a,b){if(1==this.g){if(a&&b){var c=m7(this);h7(c,a,b);p7(this,c)}r7(this,"previous")}else o7(this,g.Ra(this.kn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=m7(this);h7(c,a,b);p7(this,c)}r7(this,"next")}else o7(this,g.Ra(this.nextVideo,a,b))};
g.h.bv=function(){1==this.g?r7(this,"dismissAutoplay"):o7(this,this.bv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}l7.Ha.dispose.call(this)};
g.h.T=function(){n7(this);this.o=null;this.u.clear();k7(this,null);l7.Ha.T.call(this)};
g.h.ht=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.JJ=function(a,b){this.N(a,b)};
g.h.EH=function(a){if(!a)this.rk(null),k7(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=m7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,p7(this,b)}};
g.h.rk=function(a){c6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),s7(this),this.N("remotePlayerChange")};
g.h.DH=function(a){a?(s7(this),this.N("remotePlayerChange")):this.rk(null)};
g.h.Ls=function(){r7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.QH=function(){var a=Z6();a&&k7(this,a)};
g.h.Kb=function(a){c6("CP",a)};g.A(u7,g.O);g.h=u7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ba(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ba(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;f7(this.Pa,m);this.o="UNSUPPORTED";v7("Connecting with setPlaylist and params: "+g.Hg(l));this.g.connect({method:"setPlaylist",
params:g.Hg(l)},a,I4())}else v7("Connecting without params"),this.g.connect({},a,I4());kqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),w7(this,3));u7.Ha.dispose.call(this)};
g.h.T=function(){x7(this);z7(this);y7(this);g.Sp(this.F);this.F=NaN;g.Sp(this.H);this.H=NaN;this.l=null;g.Fr(this.O);this.O.length=0;this.g.dispose();u7.Ha.T.call(this);this.o=this.B=this.i=this.Pa=this.g=null};
g.h.NC=function(){this.A(2)};
g.h.IH=function(){v7("Channel opened");this.M&&(this.M=!1,y7(this),this.P=g.Qp((0,g.z)(function(){v7("Timing out waiting for a screen.");this.A(1)},this),15E3));
Mpa(Tpa(this.g),this.V)};
g.h.FH=function(){v7("Channel closed");isNaN(this.u)?L4(!0):L4();this.dispose()};
g.h.GH=function(a){L4();isNaN(this.D())?(v7("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,v7("Channel error: "+a+" with reconnection in "+this.D()+" ms"),w7(this,2))};
g.h.HH=function(a){a.params?v7("Received: action="+a.action+", params="+g.Hg(a.params)):v7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=q4(a.params.devices);this.i=(0,g.F)(a,function(c){return new t4(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
C7(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
C7(this,!1);break;case "remoteConnected":var b=new t4(q4(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||Apa(this.i,b);
break;case "remoteDisconnected":b=new t4(q4(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":D7(this,a);break;case "nowPlaying":nqa(this,a);break;case "onStateChange":E7(this,a);break;case "onAdStateChange":oqa(this,a);break;case "onVolumeChanged":pqa(this,a);break;case "onSubtitlesTrackChanged":mqa(this,a);break;case "nowAutoplaying":qqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.N("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":rqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:v7("Unrecognized action: "+a.action)}};
g.h.zL=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&A7(this,"getNowPlaying")}};
u7.prototype.subscribe=u7.prototype.subscribe;u7.prototype.unsubscribeByKey=u7.prototype.Af;u7.prototype.aa=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?V5(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
u7.prototype.getProxyState=u7.prototype.aa;u7.prototype.A=function(a){v7("Disconnecting with "+a);x7(this);this.N("beforeDisconnect",a);1==a&&L4();U5(this.g,a);this.dispose()};
u7.prototype.disconnect=u7.prototype.A;u7.prototype.X=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),h7(a,this.l,a.index));return i7(a)};
u7.prototype.getPlayerContextData=u7.prototype.X;
u7.prototype.ka=function(a){var b=new c7(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.Sp(this.F),this.F=g.Qp((0,g.z)(this.zL,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&g7(this.Pa)==g7(b)&&g.Hg(this.Pa.g)==g.Hg(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
u7.prototype.setPlayerContextData=u7.prototype.ka;u7.prototype.R=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
u7.prototype.getOtherConnectedRemoteId=u7.prototype.R;u7.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.C)():NaN};
u7.prototype.getReconnectTimeout=u7.prototype.D;u7.prototype.ba=function(){return this.o||"UNSUPPORTED"};
u7.prototype.getAutoplayMode=u7.prototype.ba;u7.prototype.Y=function(){return this.B||""};
u7.prototype.getAutoplayVideoId=u7.prototype.Y;u7.prototype.ua=function(){if(!isNaN(this.D())){var a=this.g.i;g.po(a.g);a.start()}};
u7.prototype.reconnect=u7.prototype.ua;u7.prototype.ga=function(a,b){A7(this,a,b);B7(this)};
u7.prototype.sendMessage=u7.prototype.ga;g.A(F7,g6);g.h=F7.prototype;g.h.Gd=function(a){return this.Fc.$_gs(a)};
g.h.contains=function(a){return!!this.Fc.$_c(a)};
g.h.get=function(a){return this.Fc.$_g(a)};
g.h.start=function(){this.Fc.$_st()};
g.h.add=function(a,b,c){this.Fc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Fc.$_r(a,b,c)};
g.h.Wn=function(a,b,c,d){this.Fc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Fc.$_ubk(this.i[a]);this.i.length=0;this.Fc=null;F7.Ha.T.call(this)};
g.h.tM=function(){this.N("screenChange")};
g.h.nJ=function(){this.N("onlineScreenChange")};
t6.prototype.$_st=t6.prototype.start;t6.prototype.$_gspc=t6.prototype.uM;t6.prototype.$_gsppc=t6.prototype.WA;t6.prototype.$_c=t6.prototype.contains;t6.prototype.$_g=t6.prototype.get;t6.prototype.$_a=t6.prototype.add;t6.prototype.$_un=t6.prototype.Wn;t6.prototype.$_r=t6.prototype.remove;t6.prototype.$_gs=t6.prototype.Gd;t6.prototype.$_gos=t6.prototype.VA;t6.prototype.$_s=t6.prototype.subscribe;t6.prototype.$_ubk=t6.prototype.Af;var G7=null,H7=null,X7=null,L7=[];g.t($7,g.G);g.h=$7.prototype;
g.h.T=function(){g.G.prototype.T.call(this);this.o.stop();this.A.stop();this.J.stop();this.M();this.g.unsubscribe("proxyStateChange",this.My,this);this.g.unsubscribe("remotePlayerChange",this.vk,this);this.g.unsubscribe("remoteQueueChange",this.cn,this);this.g.unsubscribe("autoplayUpNext",this.ny,this);this.g.unsubscribe("previousNextChange",this.Jy,this);this.g.unsubscribe("nowAutoplaying",this.Fy,this);this.g.unsubscribe("autoplayDismissed",this.my,this);this.g=this.u=null};
g.h.mx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(d8(this)){if(!m7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==m7(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Fj(c[0],c[1]);break;case "control_subtitles_set_track":e8(this,c[0]);break;case "control_set_audio_track":c=c[0],d8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();f8(this,0==c?void 0:c);break;case "control_seek":f8(this,c[0]);break;case "control_subtitles_set_track":e8(this,c[0]);break;case "control_set_audio_track":c=c[0],d8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.CH=function(a){this.J.JC(a)};
g.h.eM=function(a){this.mx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.iA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||e8(this,a)};
g.h.By=function(a){if(d8(this)){this.g.unsubscribe("remotePlayerChange",this.vk,this);var b=Math.round(a.volume);a=!!a.muted;var c=m7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.vk,this)}};
g.h.CI=function(){g.Xb(this.B)||g8(this,this.B);this.D=!1};
g.h.My=function(a,b){this.A.stop();2==b&&this.hA()};
g.h.vk=function(){if(d8(this)){this.o.stop();var a=m7(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.rm=1;break;case 1082:case 1083:this.u.rm=0;break;default:this.u.rm=-1}switch(a.playerState){case 1081:case 1:b8(this,new g.FC(8));this.gA();break;case 1085:case 3:b8(this,new g.FC(9));break;case 1083:case 0:b8(this,new g.FC(2));this.H.stop();a8(this,this.i.getVideoData().lengthSeconds);break;case 1084:b8(this,new g.FC(4));break;case 2:b8(this,new g.FC(4));a8(this,g7(a));
break;case -1:b8(this,new g.FC(64));break;case -1E3:b8(this,new g.FC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=m7(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,g8(this,a));a=m7(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.HA()}else c8(this)};
g.h.Jy=function(){this.i.N("mdxpreviousnextchange")};
g.h.cn=function(){d8(this)||c8(this)};
g.h.VB=function(){this.g.bv()};
g.h.ny=function(a){a&&(a=g.Fq("/watch_queue_ajax",{method:"GET",Bc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.OK,this)}))&&(this.M=(0,g.z)(a.abort,a))};
g.h.OK=function(a,b){var c=new g.LA(g.V(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Fy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.my=function(){this.i.N("mdxautoplaycanceled")};
g.h.iF=function(a,b){-1==m7(this.g).playerState?f8(this,a):b&&this.g.seekTo(a)};
g.h.HA=function(){if(d8(this)){var a=m7(this.g);this.l.Oa(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.By)}};
g.h.gA=function(){this.o.stop();if(!this.g.ea()){var a=m7(this.g);1==a.playerState&&b8(this,new g.FC(8));a8(this,g7(a));this.o.start()}};
g.h.hA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(j8,g.T);j8.prototype.u=function(a){i8(this,a.state)};g.t(k8,g.cT);k8.prototype.J=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.tb(a,this.A,this),g.dT(this,(0,g.F)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.le(this.A(a)),this.enable(!0)):this.enable(!1)};
k8.prototype.A=function(a){return a.key};
k8.prototype.ke=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
k8.prototype.Ic=function(a){g.cT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.ib()};g.t(l8,g.$J);g.h=l8.prototype;g.h.create=function(){wqa(g.Dy(g.V(this.player)));this.u.push(g.Xp("yt-remote-before-disconnect",this.yH,this));this.u.push(g.Xp("yt-remote-connection-change",this.RJ,this));this.u.push(g.Xp("yt-remote-receiver-availability-change",this.Ky,this));this.u.push(g.Xp("yt-remote-auto-connect",this.PJ,this));this.u.push(g.Xp("yt-remote-receiver-resumed",this.OJ,this));this.Ky()};
g.h.load=function(){this.player.cancelPlayback();g.$J.prototype.load.call(this);this.o=new $7(this,this.player,this.g);var a=(a=Z7())?a.currentTime:0;var b=W7()?new l7(R7(),void 0):null;0==a&&b&&(a=g7(m7(b)));0!=a&&this.pd(a);h8(this,this.ek,this.ek);g.gX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.o,this.g);this.g=this.o=null;g.$J.prototype.unload.call(this);g.gX(this.player.app,5)};
g.h.T=function(){g.Yp(this.u);g.$J.prototype.T.call(this)};
g.h.Re=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.mx.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.rm};
g.h.FC=function(){return this.loaded?this.o.suggestion:null};
g.h.Ge=function(){return this.g?m7(this.g).Ge:!1};
g.h.hasNext=function(){return this.g?m7(this.g).hasNext:!1};
g.h.pd=function(a,b){this.D=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=m7(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.V(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Zb():!a.isAdPlaying()&&this.player.Zb(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+e7(a):a.l,isAtLiveHead:1>=(a.u?a.i+e7(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+e7(a):a.i,seekableStart:0<a.o?a.o+
e7(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.kn=function(){this.g&&this.g.kn()};
g.h.yH=function(a){1==a&&(this.B=this.g?m7(this.g):null)};
g.h.RJ=function(){var a=W7()?new l7(R7(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,g7(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Ky=function(){this.A=[this.i].concat(xqa());var a=S7()||this.i;m8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.PJ=function(){var a=S7();m8(this,a)};
g.h.OJ=function(){this.l=S7()};
g.h.Wb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?a7():m8(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&a7(),!0):!1}};
g.h.Ls=function(){this.g.Ls()};
g.h.Nb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.tU.remote=l8;})(_yt_player);
